# Generated by Django 4.2.7 on 2023-11-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Nombre')),
                ('desc', models.TextField(default='', max_length=512, verbose_name='Descripcción del puesto de trabajo')),
            ],
            options={
                'verbose_name': 'Frente de obra',
                'verbose_name_plural': 'Listado de frentes de obra',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=32, null=True, verbose_name='Nombre del edificio')),
                ('desc', models.TextField(default='Sin descripción', max_length=64, null=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name_plural': 'Edificios',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=32, verbose_name='Apellido paterno')),
                ('maternal_last_name', models.CharField(max_length=32, verbose_name='Apellido materno')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='R.F.C.')),
                ('email', models.CharField(max_length=32, verbose_name='Correo eléctronico')),
                ('birthdate', models.DateField(verbose_name='Fecha de cumpleaños')),
                ('gender', models.CharField(choices=[('MAN', 'Hombre'), ('WOMAN', 'Mujer'), ('HELICOPTERO DE GUERRA', 'Tanque táctico')], default='Patata', max_length=32, verbose_name='Género')),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Casado/Casada/Quesadilla'), ('SINGLE', 'Soltero/Soltera/Soltere'), ('WIDOWER', 'Viudo/Viuda/Natasha')], default='Aceite de oliva', max_length=32, verbose_name='Estado civil')),
                ('phone', models.CharField(max_length=10, verbose_name='Número de teléfono')),
                ('clabe', models.CharField(max_length=32, verbose_name='CLABE bancaria')),
                ('salary', models.IntegerField(default=0, verbose_name='Salario')),
                ('rol', models.CharField(choices=[('SUPERINTENDENT', 'Super-intendente'), ('DIRECTOR', 'Director'), ('RESIDENT', 'Residente'), ('SUPERVISOR', 'Supervisor')], default='Sin definir', max_length=32, verbose_name='Puesto de trabajo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
