# Generated by Django 4.2.5 on 2023-09-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=32, null=True)),
                ('desc', models.TextField(default='Sin descripcción', max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Edificios',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('maternal_last_name', models.CharField(max_length=32)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(max_length=32)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('MAN', 'Hombre'), ('WOMAN', 'Mujer'), ('HELICOPTERO DE GUERRA', 'Tanque táctico')], default='Patata', max_length=32)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Casado/Casada/Quesadilla'), ('SINGLE', 'Soltero/Soltera/Soltere'), ('WIDOWER', 'Viudo/Viuda/Natasha')], default='Aceite de oliva', max_length=32)),
                ('phone', models.CharField(max_length=10)),
                ('clabe', models.CharField(max_length=32)),
                ('salary', models.IntegerField(default=0)),
                ('rol', models.CharField(choices=[('SUPERINTENDENT', 'Super-intendente'), ('DIRECTOR', 'Director'), ('RESIDENT', 'Residente'), ('SUPERVISOR', 'Supervisor')], default='Sin definir', max_length=32)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
