# Generated by Django 4.2.7 on 2023-11-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0002_stafffile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stafffile",
            options={
                "verbose_name": "Archivo de empleados",
                "verbose_name_plural": "Listado de archivos de empleados",
            },
        ),
        migrations.RemoveField(
            model_name="stafffile",
            name="registration_date",
        ),
        migrations.AlterField(
            model_name="users",
            name="gender",
            field=models.CharField(
                choices=[("Hombre", "Hombre"), ("Mujer", "Mujer")],
                default="Patata",
                max_length=32,
                verbose_name="Género",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="marital_status",
            field=models.CharField(
                choices=[("Casado(a)", "Casado(a)"), ("Soltero(a)", "Soltero(a)")],
                default="Aceite de oliva",
                max_length=32,
                verbose_name="Estado civil",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="rol",
            field=models.CharField(
                choices=[
                    ("Super-intendente", "Super-intendente"),
                    ("Director", "Director"),
                    ("Residente", "Residente"),
                    ("Supervisor", "Supervisor"),
                ],
                default="Sin definir",
                max_length=32,
                verbose_name="Puesto de trabajo",
            ),
        ),
    ]
