# Generated by Django 4.2.7 on 2023-11-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0003_alter_stafffile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="birthdate",
            field=models.CharField(max_length=32, verbose_name="Fecha de nacimiento"),
        ),
    ]
