# Generated by Django 4.2.7 on 2023-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0004_alter_users_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="birthdate",
            field=models.DateField(verbose_name="Fecha de nacimiento"),
        ),
    ]
