# Generated by Django 4.2.7 on 2023-11-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre del plano')),
                ('blueprint', models.FileField(upload_to='gobierno/building/blueprints/', verbose_name='Archivo de plano')),
                ('desc', models.TextField(max_length=1024, verbose_name='Explicación detallada acerca del plano (Obligatorio)')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Listado de planos',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Nombre del material')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad disponible')),
                ('price', models.IntegerField(default=0, verbose_name='Precio unitario')),
                ('method', models.CharField(choices=[('bulk', 'Granel'), ('l', 'Litros'), ('kg', 'Kilogramos'), ('package', 'Bultos/Costales')], max_length=32, verbose_name='Tipo de venta')),
                ('desc', models.TextField(blank=True, default='', max_length=512, verbose_name='Descripcción del material')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Listado de notas',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Breve descripcción de la nota')),
                ('desc', models.TextField(blank=True, default='', max_length=512, verbose_name='Descripcción completa sobre la nota')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Listado de notas',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('SUPERINTENDENT', 'Super-intendente'), ('DIRECTOR', 'Director'), ('RESIDENT', 'Residente'), ('SUPERVISOR', 'Supervisor')], default='Sin definir', max_length=32, verbose_name='Nivel de jerarquía')),
                ('desc', models.TextField(blank=True, default='', max_length=512, verbose_name='Descripcción sobre el responsable')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.jobrole', verbose_name='Puesto de trabajo')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.users', verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Listado de responsables',
            },
        ),
    ]
