# Generated by Django 4.2.7 on 2023-11-25 01:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="Nombre del plano"),
                ),
                (
                    "blueprint",
                    models.FileField(
                        upload_to="gobierno/building/blueprints/",
                        verbose_name="Archivo de plano",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        max_length=1024,
                        verbose_name="Explicación detallada acerca del plano (Obligatorio)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano",
                "verbose_name_plural": "Listado de planos",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="media/doc/",
                        verbose_name="Ingrese el documento para autollenar todos los formularios",
                    ),
                ),
                ("registration_date", models.DateField(blank=True, editable=False)),
            ],
            options={
                "verbose_name": "Archivo",
                "verbose_name_plural": "Listado de archivos",
            },
        ),
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "electrical_buget",
                    models.IntegerField(
                        default=0,
                        verbose_name="Presupuesto de la instalación eléctrica",
                    ),
                ),
                (
                    "water_budget",
                    models.IntegerField(
                        default=0, verbose_name="Presupuesto para instalación hidrica"
                    ),
                ),
                (
                    "mobilary_budget",
                    models.IntegerField(
                        default=0, verbose_name="Presupuesto para inmobiliario"
                    ),
                ),
                (
                    "floor_budget",
                    models.IntegerField(
                        default=0, verbose_name="Presupuesto para el suelo"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(verbose_name="Fecha estimada de entrega"),
                ),
                ("registration_date", models.DateField(blank=True)),
            ],
            options={
                "verbose_name": "Registo de presupuesto",
                "verbose_name_plural": "Listado de presupuestos",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=32, verbose_name="Nombre del material"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Cantidad disponible"),
                ),
                (
                    "price",
                    models.IntegerField(default=0, verbose_name="Precio unitario"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bulk", "Granel"),
                            ("l", "Litros"),
                            ("kg", "Kilogramos"),
                            ("package", "Bultos/Costales"),
                        ],
                        max_length=32,
                        verbose_name="Tipo de venta",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Descripcción del material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Listado de notas",
            },
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "general_progress",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("general_budget", models.IntegerField(blank=True, default=0)),
                ("material_budget", models.IntegerField(blank=True, default=0)),
            ],
            options={
                "verbose_name": "Metadata",
                "verbose_name_plural": "Metadatas",
            },
        ),
        migrations.CreateModel(
            name="Overview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        max_length=32,
                        verbose_name="Breve descripcción de la nota",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Descripcción completa sobre la nota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Listado de notas",
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("SUPERINTENDENT", "Super-intendente"),
                            ("DIRECTOR", "Director"),
                            ("RESIDENT", "Residente"),
                            ("SUPERVISOR", "Supervisor"),
                        ],
                        default="Sin definir",
                        max_length=32,
                        verbose_name="Nivel de jerarquía",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Descripcción sobre el responsable",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.jobrole",
                        verbose_name="Puesto de trabajo",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.users",
                        verbose_name="Nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable",
                "verbose_name_plural": "Listado de responsables",
            },
        ),
    ]
