# Generated by Django 4.2.7 on 2023-11-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobierno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrical_buget', models.IntegerField(default=0, verbose_name='Presupuesto de la instalación eléctrica')),
                ('water_budget', models.IntegerField(default=0, verbose_name='Presupuesto para instalación hidrica')),
                ('mobilary_budget', models.IntegerField(default=0, verbose_name='Presupuesto para inmobiliario')),
                ('floor_budget', models.IntegerField(default=0, verbose_name='Presupuesto para el suelo')),
                ('release_date', models.DateField(verbose_name='Fecha estimada de entrega')),
                ('registration_date', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Registo de presupuesto',
                'verbose_name_plural': 'Listado de presupuestos',
            },
        ),
    ]
