# Generated by Django 4.2.7 on 2023-11-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobierno', '0002_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('general_progress', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Metadata',
                'verbose_name_plural': 'Metadatas',
            },
        ),
    ]
