# Generated by Django 4.2.7 on 2023-11-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gobierno", "0003_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="media/doc/",
                        verbose_name="Ingrese el documento para autollenar todos los formularios",
                    ),
                ),
                ("registration_date", models.DateField(blank=True)),
            ],
            options={
                "verbose_name": "Archivo",
                "verbose_name_plural": "Listado de archivos",
            },
        ),
    ]
