# Generated by Django 4.2.7 on 2023-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gobierno", "0004_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="registration_date",
            field=models.DateField(blank=True, editable=False),
        ),
    ]
