# Generated by Django 4.2.7 on 2023-11-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gobierno", "0004_metadata_aplanado_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
